{{ config(materialized='table') }}

SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD')) AS SK_DATE,
    DATE_VALUE,
    YEAR(DATE_VALUE) AS YEAR,
    QUARTER(DATE_VALUE) AS QUARTER,
    MONTH(DATE_VALUE) AS MONTH
FROM (
    SELECT DATEADD(
        DAY,
        SEQ4(),
        '2020-01-01'::DATE
    ) AS DATE_VALUE
    FROM TABLE(GENERATOR(ROWCOUNT => 3653))
)