-- SELECT 
--     RAW_DATA:"$1":::VARCHAR AS BRANCH_ID,
--     RAW_DATA:"$2":::VARCHAR AS BRANCH_NAME,
--     RAW_DATA:"$3":::VARCHAR AS REGION,
--     RAW_DATA:"$4":::VARCHAR AS CITY,
--     RAW_DATA:"$5":::VARCHAR AS STATE,
--     RAW_DATA:"$6":::VARCHAR AS COUNTRY,
--     TRY_TO_DATE(RAW_DATA:"$7":::VARCHAR, 'YYYY-MM-DD') AS OPEN_DATE,
--     RAW_DATA:"$8":::VARCHAR AS STATUS,
--     LOAD_TS
-- FROM {{ source('raw', 'RAW_BRANCHES') }}

SELECT
    RAW_DATA:"$1"::VARCHAR AS BRANCH_ID,
    RAW_DATA:"$2"::VARCHAR AS BRANCH_NAME,
    RAW_DATA:"$3"::VARCHAR AS REGION,
    RAW_DATA:"$4"::VARCHAR AS CITY,
    RAW_DATA:"$5"::VARCHAR AS STATE,
    RAW_DATA:"$6"::VARCHAR AS COUNTRY,
    TRY_TO_DATE(RAW_DATA:"$7"::VARCHAR, 'YYYY-MM-DD') AS OPEN_DATE,
    RAW_DATA:"$8"::VARCHAR AS STATUS,
    LOAD_TS
FROM {{ source('raw', 'RAW_BRANCHES') }}