-- SELECT 
--     RAW_DATA:"$1":::VARCHAR AS BORROWER_ID,
--     RAW_DATA:"$2":::VARCHAR AS FIRST_NAME,
--     RAW_DATA:"$3":::VARCHAR AS LAST_NAME,
--     RAW_DATA:"$4":::VARCHAR AS EMAIL,
--     RAW_DATA:"$5":::VARCHAR AS PHONE,
--     RAW_DATA:"$6":::VARCHAR AS SEGMENT,
--     RAW_DATA:"$7":::VARCHAR AS CITY,
--     RAW_DATA:"$8":::VARCHAR AS STATE,
--     RAW_DATA:"$9":::VARCHAR AS COUNTRY,
--     TRY_TO_DATE(RAW_DATA:"$10":::VARCHAR, 'YYYY-MM-DD') AS DOB,
--     RAW_DATA:"$11":::VARCHAR AS EMPLOYMENT_TYPE,
--     LOAD_TS
-- FROM {{ source('raw', 'RAW_BORROWERS') }}

SELECT
    RAW_DATA:"$1"::VARCHAR AS BORROWER_ID,
    RAW_DATA:"$2"::VARCHAR AS FIRST_NAME,
    RAW_DATA:"$3"::VARCHAR AS LAST_NAME,
    RAW_DATA:"$4"::VARCHAR AS EMAIL,
    RAW_DATA:"$5"::VARCHAR AS PHONE,
    RAW_DATA:"$6"::VARCHAR AS SEGMENT,
    RAW_DATA:"$7"::VARCHAR AS CITY,
    RAW_DATA:"$8"::VARCHAR AS STATE,
    RAW_DATA:"$9"::VARCHAR AS COUNTRY,
    TRY_TO_DATE(RAW_DATA:"$10"::VARCHAR, 'YYYY-MM-DD') AS DOB,
    RAW_DATA:"$11"::VARCHAR AS EMPLOYMENT_TYPE,
    LOAD_TS
FROM {{ source('raw', 'RAW_BORROWERS') }}