-- SELECT 
--     RAW_DATA:"$1":::VARCHAR AS LOAN_ID,
--     RAW_DATA:"$2":::VARCHAR AS BORROWER_ID,
--     RAW_DATA:"$3":::VARCHAR AS BRANCH_ID,
--     RAW_DATA:"$4":::VARCHAR AS LOAN_TYPE,
--     TRY_TO_NUMBER(RAW_DATA:"$5":::VARCHAR, 18, 2) AS PRINCIPAL_AMOUNT,
--     TRY_TO_NUMBER(RAW_DATA:"$6":::VARCHAR, 5, 2) AS INTEREST_RATE,
--     TRY_TO_NUMBER(RAW_DATA:"$7":::VARCHAR) AS TENURE_MONTHS,
--     TRY_TO_DATE(RAW_DATA:"$8":::VARCHAR, 'YYYY-MM-DD') AS DISBURSE_DATE,
--     RAW_DATA:"$9":::VARCHAR AS LOAN_STATUS,
--     RAW_DATA:"$10":::VARCHAR AS SECURITY_TYPE,
--     TRY_TO_TIMESTAMP_NTZ(RAW_DATA:"$11":::VARCHAR) AS UPDATED_AT,
--     LOAD_TS
-- FROM {{ source('raw', 'RAW_LOANS') }}

SELECT
    RAW_DATA:"$1"::VARCHAR AS LOAN_ID,
    RAW_DATA:"$2"::VARCHAR AS BORROWER_ID,
    RAW_DATA:"$3"::VARCHAR AS BRANCH_ID,
    RAW_DATA:"$4"::VARCHAR AS LOAN_TYPE,
    TRY_TO_NUMBER(RAW_DATA:"$5"::VARCHAR, 18, 2) AS PRINCIPAL_AMOUNT,
    TRY_TO_NUMBER(RAW_DATA:"$6"::VARCHAR, 5, 2) AS INTEREST_RATE,
    TRY_TO_NUMBER(RAW_DATA:"$7"::VARCHAR) AS TENURE_MONTHS,
    TRY_TO_DATE(RAW_DATA:"$8"::VARCHAR, 'YYYY-MM-DD') AS DISBURSE_DATE,
    RAW_DATA:"$9"::VARCHAR AS LOAN_STATUS,
    RAW_DATA:"$10"::VARCHAR AS SECURITY_TYPE,
    TRY_TO_TIMESTAMP_NTZ(RAW_DATA:"$11"::VARCHAR) AS UPDATED_AT,
    LOAD_TS
FROM {{ source('raw', 'RAW_LOANS') }}