-- SELECT 
--     RAW_DATA:"$1":::VARCHAR AS TXN_ID,
--     TRY_TO_NUMBER(RAW_DATA:"$2":::VARCHAR) AS TXN_LINE_ID,
--     TRY_TO_DATE(RAW_DATA:"$3":::VARCHAR, 'YYYY-MM-DD') AS TXN_DATE,
--     RAW_DATA:"$4":::VARCHAR AS LOAN_ID,
--     RAW_DATA:"$5":::VARCHAR AS BORROWER_ID,
--     RAW_DATA:"$6":::VARCHAR AS BRANCH_ID,
--     RAW_DATA:"$7":::VARCHAR AS TXN_TYPE,
--     TRY_TO_NUMBER(RAW_DATA:"$8":::VARCHAR, 18, 2) AS AMOUNT,
--     TRY_TO_NUMBER(RAW_DATA:"$9":::VARCHAR, 18, 2) AS INTEREST_COMPONENT,
--     TRY_TO_NUMBER(RAW_DATA:"$10":::VARCHAR, 18, 2) AS FEE_COMPONENT,
--     RAW_DATA:"$11":::VARCHAR AS PAYMENT_MODE,
--     RAW_DATA:"$12":::VARCHAR AS TXN_STATUS,
--     LOAD_TS
-- FROM {{ source('raw', 'RAW_LOAN_TXN') }}

SELECT
    RAW_DATA:"$1"::VARCHAR AS TXN_ID,
    TRY_TO_NUMBER(RAW_DATA:"$2"::VARCHAR) AS TXN_LINE_ID,
    TRY_TO_DATE(RAW_DATA:"$3"::VARCHAR, 'YYYY-MM-DD') AS TXN_DATE,
    RAW_DATA:"$4"::VARCHAR AS LOAN_ID,
    RAW_DATA:"$5"::VARCHAR AS BORROWER_ID,
    RAW_DATA:"$6"::VARCHAR AS BRANCH_ID,
    RAW_DATA:"$7"::VARCHAR AS TXN_TYPE,
    TRY_TO_NUMBER(RAW_DATA:"$8"::VARCHAR, 18, 2) AS AMOUNT,
    TRY_TO_NUMBER(RAW_DATA:"$9"::VARCHAR, 18, 2) AS INTEREST_COMPONENT,
    TRY_TO_NUMBER(RAW_DATA:"$10"::VARCHAR, 18, 2) AS FEE_COMPONENT,
    RAW_DATA:"$11"::VARCHAR AS PAYMENT_MODE,
    RAW_DATA:"$12"::VARCHAR AS TXN_STATUS,
    LOAD_TS
FROM {{ source('raw', 'RAW_LOAN_TXN') }}